### ISSUE TITLE
WHF?

### ISSUE THREAD

**Issue by nordby** [msmith93/brenda#8]
brenda-run -i c1.xlarge -N 1 demand
----------------------------
AMI ID: ami-03bb972b1aa6051db
Instance type: c1.xlarge
Max instances: 1
Instance store device: /dev/sdb
SSH key name: brenda
Security groups: ('brenda',)
Startup Script:
   IyEvYmluL2Jhc2gKIyBydW4gQnJlbmRhIG9uIHRoZSBFQzIgaW5zdGFuY2Ugc3RvcmUgdm9sdW1lCkI9Ii9tbnQvYnJlbmRhIgppZiAhIFsgLWQgIiRCIiBdOyB0aGVuCiAgZm9yIGYgaW4gYnJlbmRhLnBpZCBsb2cgdGFza19jb3VudCB0YXNrX2xhc3QgRE9ORSA7IGRvCiAgICBsbiAtcyAiJEIvJGYiICIvcmZpCmV4cG9ydCBCUkVOREFfV09SS19ESVI9Ii4iCm1rZGlyIC1wICIkQiIKY2QgIiRCIgovdXNyL2xvY2FsL2Jpbi9icmVuZGEtbm9kZSAtLWRhZW1vbiA8PEVPRgpBV1NfQUNDRVNTX0tFWT1BS0lBSUNYU1RUWkVXRE9GWFQ1QQpBV1NfU0VDUkVUX0tFWT1XQVBlekJTd29NeWpPNGhkVVlGUUdxaXViYlBqV1E0ZzhkR293VFArCkJMRU5ERVJfUFJPSkVDVD1zMzovL25vcmRvcnNoYS9teXByb2plY3QudGFyLmd6CldPUktfUVVFVUU9c3FzOi8vbm9yZF9vcnNoYV9kb25lClJFTkRFUl9PVVRQVVQ9czM6Ly9ub3Jkb3JzaGFkb25lCkRPTkU9c2h1dGRvd24KRU9GCg==
Traceback (most recent call last):
  File "/usr/local/bin/brenda-run", line 172, in <module>
    main()
  File "/usr/local/bin/brenda-run", line 151, in main
    run.demand(opts, conf)
  File "/usr/local/lib/python3.9/site-packages/brenda/run.py", line 58, in demand
    reservation = ec2.create_instances(**run_args)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 573, in __getattr__
    raise AttributeError(
AttributeError: 'EC2' object has no attribute 'create_instances'

**Comment by msmith93** [comment]
Thanks for opening the issue @nordby. This was something that was missed during the transition to boto3. I merged a PR that should fix this issue for you: https://github.com/msmith93/brenda/pull/9
If you'd like the fix, please pull the latest from master, re-install brenda, and re-run your command.

**Comment by msmith93** [comment]
It looks like there are still issues with some other sub-commands. I'm still investigating

**Comment by msmith93** [comment]
Fixed some other commands that were failing because of methods not being ported to boto3: https://github.com/msmith93/brenda/commit/6950413f0c52cc127f7ef4ebe72ac3d76909c4ce
